server:
  grpcPort: "50051"
  httpPort: "8081"

redis:
  url: "redis://:localpassword@172.20.0.13:6379/0"

rabbitmq:
  url: "amqp://admin:admin@172.20.0.14:5672/"
  consumers:
    defaultCount: 5
  topology:
    exchanges:
      - name: "gateway_service.v1.events"
        type: "topic"
        durable: true
    queues:
      cv_requests:
        name: "content_service.v1.cv_requests"
        durable: true
        dlq: "content_service.v1.cv_requests.dlq"
      cv_requests_dlq:
        name: "content_service.v1.cv_requests.dlq"
        durable: true
    bindings:
      - exchange: "gateway_service.v1.events"
        queue_key: "cv_requests"
        routing_key: "cv.request.*"

content:
  defaultLang: "pl"
  files:
    pl: "content/pl.json"
    en: "content/en.json"

cv:
  filePath: "/app/private/cv.pdf"
  password: "local_password"
  tokenTTLSeconds: 60
