server:
  grpcPort: "50051"
  httpPort: "8081"
redis:
  addr: "redis:6379"
rabbitmq:
  url: "amqp://admin:admin@rabbitmq:5672/"
  cvRequestQueue: "content_service.v1.cv_requests"
content:
  path: "content"
cv:
  filePath: "/app/private/cv.pdf"
  password: ""
  tokenTTLSeconds: 60